# default_stages: [commit, push]
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # check and format the syntax
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        # - id: check-yaml
        exclude: ^deployment/kubernetes/charts
      - id: check-toml
      - id: check-xml
      - id: double-quote-string-fixer
      # environment checker
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # check the git-related commit or object
      - id: check-merge-conflict
      - id: check-added-large-files
      # check sensitive information
      - id: debug-statements
      - id: detect-private-key

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports # TODO: remove this

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - --profile=black
          - --filter-files

  # - repo: https://github.com/psf/black
  #   rev: 23.11.0
  #   hooks:
  #     - id: black
  #       language_version: python3.11
  #       args:
  #         - --target-version=py311
  #         - --line-length=120
  #         - --skip-string-normalization

  # - repo: https://github.com/zricethezav/gitleaks
  #   rev: v8.18.1
  #   hooks:
  #     - id: gitleaks
  #       # run the detect mode and show all the leak credentials
  #       entry: gitleaks detect --verbose --redact

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
