apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrate-env
  labels:
    {{- include "project.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  {{- range $key, $val := .Values.infraEnv }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

  {{- range $key, $val := .Values.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
