{{- if .Values.internalIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
  {{- with .Values.internalIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.internalIngress.className }}
  rules:
    - host: {{ .Values.internalIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
