{{- if .Values.app.migratedJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate
  labels:
    {{- include "project.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      nodeSelector:
        {{- toYaml .Values.app.nodeSelector | nindent 8 }}
      containers:
        - name: migrate-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.app.migratedJob.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-migrate-env
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
