version: "3.3"
services:
    elastic:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment: 
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
    rails:
        build: ./csl/
        container_name: csl
        environment:
            - RECREATE_DB=true
        ports:
            - "3000:3000"
        depends_on:
            - elastic
