version: "3.3"
services:
    elastic:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        environment: 
            - discovery.type=single-node
    rails:
        build:
            context: ./../
            dockerfile: $PWD/csl/Dockerfile
        container_name: csl
        environment:
            - RECREATE_DB=true
        ports:
            - "3000:3000"
        depends_on:
            - elastic
