version: "3.8"
services:
    elastic:
        container_name: csl-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
        restart: on-failure
        environment:
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 9200:9200
          - 9300:9300
        volumes:
            - elastic:/usr/share/elasticsearch/data
    kibana:
        container_name: csl-kibana
        image: docker.elastic.co/kibana/kibana:7.17.16
        restart: on-failure
        links:
          - elastic:elasticsearch
        ports:
          - 5601:5601
        depends_on:
            - elastic
        volumes:
          - kibana:/usr/share/kibana/data

    rails:
        build:
            context: ./../
            dockerfile: $PWD/csl/Dockerfile
        container_name: csl-api
        environment:
            - RECREATE_DB=true
            - SECRET_KEY_BASE=fake-key
            - ELASTICSEARCH_URL=elastic:9200
        command: ["tail", "-f", "/dev/null"]
        volumes:
          - $PWD/../:/app
        ports:
          - 3000:3000
        depends_on:
            - elastic

    python:
        build:
            context: ./csl-python/
            dockerfile: $PWD/csl-python/Dockerfile
        container_name: csl-python
        environment:
            - RECREATE_DB=true
            - ELASTICSEARCH_URL=http://elastic:9200
        depends_on:
            - rails
            - elastic

volumes:
    elastic:
    kibana:
