version: "3.3"
services:
    elastic:
        container_name: elasticsearch
        # user: $USER
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
        volumes:
            - ./es_data:/usr/share/elasticsearch/data
        environment: 
            - discovery.type=single-node
    rails:
        build:
            context: ./../
            dockerfile: $PWD/csl/Dockerfile
        container_name: csl
        environment:
            - RECREATE_DB=true
        depends_on:
            - elastic
    python:
        build: ./csl-python/
        container_name: csl-python
        depends_on:
            - elastic
    csl-proxy:
        build: ./nginx/
        container_name: csl-proxy
        volumes:
            - "./nginx/ssl/:/ssl/:ro"
            - "./nginx/conf.d/:/etc/nginx/conf.d/:ro"
        ports:
            - "${HTTPS_PORT:-11999}:11999"
        logging:
          driver: json-file
          options:
            max-size: "30m"
            max-file: "10"
        depends_on:
            - rails