env:
    ENVIRONMENT: production
    ENC_SECRET_KEY_BASE: ENC[AES256_GCM,data:8v3v8DO4FXEzXVZgWjPtWDJL+gcvXWTis7rp2JPh8yQ=,iv:34yDnJDRg8AXzRtSERAeScGeitj/oV7/AyZ4AS6ut3s=,tag:Sq3SPPPlXtlLbNYRAt+byw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:478041131377:key/d222752c-be9f-4945-b17f-a52f694bc8ef
          created_at: "2024-01-05T08:31:07Z"
          enc: AQICAHjrC1N+BaDn8oOmDbPP/08kRoh4Co3gLg7rtUmicxHcsQG+LMju4t3atT+l5VQSSIXkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMX6ajGKHE+G9Tes+EAgEQgDuXyUD1z7eZlOF6fNMQjJkBu9mUzdk8xpyizIDdE8W9iUCuocYZk9sVepHQLgfzYnbN7Ojs8bVhDtHVyw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-05T08:31:08Z"
    mac: ENC[AES256_GCM,data:AJ/Jh0tnT7fRM98F+LgMnpxZBk1Y6dDikN60HTiNaPdCIQOBEYUvcc6LKBhJpV2vg9sueDyGd5qIsD4tIpuTolpQYxvpQJR5+H4bTvR2GvGSCh7K/gaFVQ1V7XfFM/Golnx7NEdYBRnpIinL572kDPGk0z0GCsUwyXK0SnuRKBQ=,iv:CY4wQ+oM9efEOnpbiQxXVJyH1wp2SHTzSes1IIFKDn4=,tag:Pw7xopYxLqgrcvSyA32PrA==,type:str]
    pgp: []
    encrypted_regex: ^ENC
    version: 3.8.1
